export const DATABASE_CONNECTION = 'DATABASE_CONNECTION';
export const USER_REPOSITORY = 'USER_REPOSITORY';
export const ORGANISATION_REPOSITORY = 'ORGANISATION_REPOSITORY';
export const CATEGORY_REPOSITORY = 'CATEGORY_REPOSITORY';
export const NOTE_REPOSITORY = 'NOTE_REPOSITORY';
